import { IngredientItem, NutritionInfo } from '../recipes/recipe.entity';

export interface RecipeSeed {
  legacyId: string;
  name: string;
  emoji: string;
  imageUrl: string;
  category: string;
  country: string;
  cookTimeMinutes: number;
  prepTimeMinutes: number;
  difficulty: string;
  servings: number;
  isOfficial: boolean;
  uploaderName: string | null;
  rating: number;
  reviewCount: number;
  ingredients: string[];
  ingredientItems: IngredientItem[];
  steps: string[];
  tips: string | null;
  platingTips: string | null;
  nutrition: NutritionInfo | null;
  dietTags: string[];
  season: string;
  viewCount: number;
  isRecommended: boolean;
  videoUrl: string | null;
  createdAt: Date;
}

const NO_ITEMS: IngredientItem[] = [];

export const recipeSeeds: RecipeSeed[] = [
  {
    legacyId: '1',
    name: 'ผัดกะเพราหมูสับ',
    emoji: '🌶️',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Kapow_and_egg.jpg/1280px-Kapow_and_egg.jpg',
    category: 'อาหารจานเดียว',
    country: 'ไทย',
    cookTimeMinutes: 15,
    prepTimeMinutes: 5,
    difficulty: 'ง่าย',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.7,
    reviewCount: 312,
    ingredients: [
      'หมูสับ 250 กรัม',
      'กระเพราใบ 1 กำมือ',
      'กระเทียม 5 กลีบ',
      'พริกขี้หนู 5-10 เม็ด',
      'ซอสปรุงรส 1 ช้อนโต๊ะ',
      'ซอสหอยนางรม 1 ช้อนโต๊ะ',
      'น้ำตาลทราย 1 ช้อนชา',
      'น้ำมันพืช 2 ช้อนโต๊ะ',
      'ไข่ไก่ 1 ฟอง (สำหรับไข่ดาว)',
    ],
    ingredientItems: [
      { name: 'หมูสับ', amount: '250', unit: 'กรัม' },
      { name: 'กระเพราใบ', amount: '1', unit: 'กำมือ' },
      { name: 'กระเทียม', amount: '5', unit: 'กลีบ' },
      { name: 'พริกขี้หนู', amount: '5-10', unit: 'เม็ด' },
    ],
    steps: [
      'โขลกกระเทียมและพริกขี้หนูให้พอแหลก',
      'ตั้งกระทะใส่น้ำมัน ผัดกระเทียมพริกให้หอม',
      'ใส่หมูสับ ผัดให้สุกทั่ว',
      'ปรุงรสด้วยซอสปรุงรส ซอสหอยนางรม และน้ำตาล',
      'ใส่ใบกระเพรา ผัดให้เข้ากันแล้วปิดไฟ',
      'ทอดไข่ดาวเสิร์ฟคู่กับข้าวสวยร้อน ๆ',
    ],
    tips: 'ใช้ไฟแรง ผัดให้เร็ว กระเพราจะไม่เลือง',
    platingTips: 'ราดบนข้าวสวย วางไข่ดาวด้านบน โรยพริกแห้ง',
    nutrition: { calories: 420, protein: 28, fat: 22, carbs: 35, sugar: 2, sodium: 890 },
    dietTags: ['ฮาลาล'],
    season: 'ตลอดปี',
    viewCount: 1250,
    isRecommended: true,
    videoUrl: 'placeholder://video/pad-krapao',
    createdAt: new Date('2025-07-20'),
  },
  {
    legacyId: '2',
    name: 'ต้มยำกุ้ง',
    emoji: '🍤',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Tom_yum_kung_mae_nam.jpg/1280px-Tom_yum_kung_mae_nam.jpg',
    category: 'ต้ม/แกง',
    country: 'ไทย',
    cookTimeMinutes: 25,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 3,
    isOfficial: true,
    uploaderName: null,
    rating: 4.8,
    reviewCount: 256,
    ingredients: [
      'กุ้งสด 300 กรัม',
      'ตะไคร้ 2 ต้น',
      'ข่า 5 แผ่น',
      'ใบมะกรูด 4-5 ใบ',
      'พริกขี้หนู 8 เม็ด',
      'มะนาว 2-3 ลูก',
      'น้ำปลา 3 ช้อนโต๊ะ',
      'เห็ดฟาง 100 กรัม',
      'น้ำซุป/น้ำเปล่า 800 มล.',
      'ผักชี สำหรับโรยหน้า',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ต้มน้ำให้เดือด ใส่ตะไคร้ ข่า ใบมะกรูดทุบพอแตก',
      'ใส่เห็ดฟาง ต้มจนเดือดอีกครั้ง',
      'ใส่กุ้งสด ต้มจนกุ้งเปลี่ยนสี',
      'ปรุงรสด้วยน้ำปลา พริกขี้หนูบุบ',
      'ปิดไฟ บีบมะนาวลงไป คนให้เข้ากัน',
      'โรยผักชี เสิร์ฟร้อน ๆ',
    ],
    tips: 'อย่าต้มกุ้งนานเกินไป จะเหนียว',
    platingTips: 'เสิร์ฟในเข่งหรือหม้อ โรยผักชี',
    nutrition: { calories: 180, protein: 22, fat: 4, carbs: 8, sugar: 3, sodium: 1200 },
    dietTags: ['สุขภาพ', 'ลดน้ำหนัก'],
    season: 'ฤดูฝน',
    viewCount: 980,
    isRecommended: true,
    videoUrl: null,
    createdAt: new Date('2025-07-15'),
  },
  {
    legacyId: '3',
    name: 'ส้มตำไทย แซ่บนัวต้นตำรับ',
    emoji: '🥗',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Som_tam_thai.jpg/1280px-Som_tam_thai.jpg',
    category: 'ยำ/ตำ',
    country: 'ไทย',
    cookTimeMinutes: 15,
    prepTimeMinutes: 15,
    difficulty: 'ง่าย',
    servings: 2,
    isOfficial: false,
    uploaderName: 'แซ่บอีสานป้าแดง',
    rating: 4.9,
    reviewCount: 421,
    ingredients: [
      'มะละกอเขียวฝอย 2 ถ้วย',
      'มะเขือเทศ 3 ลูก',
      'ถั่วฝักยาว 2 ฝัก',
      'กระเทียม 4 กลีบ',
      'พริกขี้หนู 5 เม็ด',
      'กุ้งแห้ง 1 ช้อนโต๊ะ',
      'ถั่วลิสงคั่ว 2 ช้อนโต๊ะ',
      'น้ำปลา 2 ช้อนโต๊ะ',
      'น้ำตาลปี๊บ 1 ช้อนโต๊ะ',
      'มะนาว 2 ลูก',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'โขลกกระเทียมและพริกขี้หนูพอแตก',
      'ใส่ถั่วฝักยาวหั่นท่อน ทุบเบา ๆ',
      'ใส่มะเขือเทศ กุ้งแห้ง น้ำปลา น้ำตาลปี๊บ มะนาว โขลกเบา ๆ ให้เข้ากัน',
      'ใส่มะละกอเขียวฝอย โขลกคลุกให้น้ำปรุงเคลือบทั่ว',
      'ใส่ถั่วลิสงคั่ว เคล้าให้เข้ากันอีกครั้ง',
      'ชิมรสปรับตามชอบ จัดเสิร์ฟพร้อมผักสด',
    ],
    tips: 'โขลกเบา ๆ อย่าให้มะละกอเละ',
    platingTips: null,
    nutrition: { calories: 120, protein: 3, fat: 2, carbs: 18, sugar: 10, sodium: 650 },
    dietTags: ['วีแกน', 'คลีน', 'ลดน้ำหนัก'],
    season: 'ฤดูร้อน',
    viewCount: 2100,
    isRecommended: true,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '4',
    name: 'สปาเก็ตตี้คาโบนาร่า',
    emoji: '🍝',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Fresh_made_pasta_Carbonara.jpg/1280px-Fresh_made_pasta_Carbonara.jpg',
    category: 'พาสต้า',
    country: 'อิตาลี',
    cookTimeMinutes: 20,
    prepTimeMinutes: 5,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.6,
    reviewCount: 188,
    ingredients: [
      'เส้นสปาเก็ตตี้ 200 กรัม',
      'เบคอนหรือกวานชาเล 100 กรัม',
      'ไข่แดง 3 ฟอง',
      'ชีสพาเมซานขูด 50 กรัม',
      'พริกไทยดำ 1 ช้อนชา',
      'เกลือ ตามชอบ',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ต้มเส้นสปาเก็ตตี้ในน้ำเดือดเค็มจนสุกนุ่ม เก็บน้ำต้มเส้นไว้บางส่วน',
      'ทอดเบคอนในกระทะจนกรอบและมันออก',
      'ตีไข่แดงกับชีสพาเมซานในชามให้เข้ากัน',
      'ใส่เส้นที่สุกแล้วลงผัดกับเบคอนนอกไฟ',
      'เทไข่ผสมชีสลงคลุกเร็ว ๆ ใช้น้ำต้มเส้นช่วยให้ซอสข้นเนียน',
      'โรยพริกไทยดำ เสิร์ฟทันที',
    ],
    tips: 'ปิดไฟก่อนใส่ไข่ ไม่งั้นจะเป็นไข่เจียว',
    platingTips: null,
    nutrition: { calories: 550, protein: 22, fat: 28, carbs: 52, sugar: 2, sodium: 780 },
    dietTags: ['มังสวิรัติ'],
    season: 'ตลอดปี',
    viewCount: 760,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '5',
    name: 'พิซซ่ามาร์เกอริต้า สูตรเตาฟืนบ้าน',
    emoji: '🍕',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Eq_it-na_pizza-margherita_sep2005_sml.jpg/1280px-Eq_it-na_pizza-margherita_sep2005_sml.jpg',
    category: 'เบเกอรี่/ขนมปัง',
    country: 'อิตาลี',
    cookTimeMinutes: 40,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: false,
    uploaderName: 'Nonna Lucia Kitchen',
    rating: 4.8,
    reviewCount: 142,
    ingredients: [
      'แป้งพิซซ่า 1 ก้อน',
      'ซอสมะเขือเทศ 100 มล.',
      'ชีสมอสซาเรลล่า 150 กรัม',
      'ใบโหระพาสด 1 กำมือ',
      'น้ำมันมะกอก 2 ช้อนโต๊ะ',
      'เกลือ ตามชอบ',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'รีดแป้งพิซซ่าให้เป็นแผ่นบาง',
      'ทาซอสมะเขือเทศให้ทั่วแผ่นแป้ง',
      'โรยชีสมอสซาเรลล่าให้ทั่ว',
      'อบที่อุณหภูมิสูงสุดของเตาประมาณ 8-10 นาทีจนชีสฟูเหลือง',
      'โรยใบโหระพาสดและน้ำมันมะกอกหลังนำออกจากเตา',
      'หั่นเสิร์ฟทันทีตอนร้อน',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '6',
    name: 'ทีรามิสุ',
    emoji: '🍰',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Tiramisu_with_all_the_layers.jpg/1280px-Tiramisu_with_all_the_layers.jpg',
    category: 'ของหวาน',
    country: 'อิตาลี',
    cookTimeMinutes: 30,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.7,
    reviewCount: 97,
    ingredients: [
      'คุกกี้เลดี้ฟิงเกอร์ 200 กรัม',
      'ชีสมาสคาร์โปเน่ 250 กรัม',
      'ไข่แดง 3 ฟอง',
      'น้ำตาลทราย 60 กรัม',
      'กาแฟเอสเพรสโซ่ 200 มล. (ทิ้งให้เย็น)',
      'ผงโกโก้ สำหรับโรยหน้า',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ตีไข่แดงกับน้ำตาลจนฟูข้น ใส่ชีสมาสคาร์โปเน่คนให้เข้ากัน',
      'จุ่มคุกกี้เลดี้ฟิงเกอร์ในกาแฟเย็นเร็ว ๆ เรียงชั้นแรกในถาด',
      'ทาครีมชีสทับให้ทั่ว',
      'เรียงคุกกี้ชั้นที่สองแล้วทาครีมทับอีกครั้ง',
      'แช่เย็นอย่างน้อย 4 ชั่วโมง',
      'โรยผงโกโก้ก่อนเสิร์ฟ',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '7',
    name: 'ราเมนซีอิ๊วดำ',
    emoji: '🍜',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29.jpg/1280px-Shoyu_ramen%2C_at_Kasukabe_Station_%282014.05.05%29.jpg',
    category: 'เส้น/ซุป',
    country: 'ญี่ปุ่น',
    cookTimeMinutes: 45,
    prepTimeMinutes: 20,
    difficulty: 'ยาก',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.6,
    reviewCount: 134,
    ingredients: [
      'เส้นราเมน 2 ก้อน',
      'น้ำสต๊อกหมู/ไก่ 1 ลิตร',
      'ซีอิ๊วญี่ปุ่น 4 ช้อนโต๊ะ',
      'หมูชาชู 4-6 แผ่น',
      'ไข่ออนเซ็น 2 ฟอง',
      'ต้นหอมซอย และสาหร่ายโนริ สำหรับโรยหน้า',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ต้มน้ำสต๊อกให้ร้อนจัด ปรุงรสด้วยซีอิ๊วญี่ปุ่น',
      'ลวกเส้นราเมนตามเวลาที่กำหนดบนบรรจุภัณฑ์',
      'ใส่เส้นลงในชาม เทน้ำซุปร้อน ๆ ลงไป',
      'จัดหมูชาชูและไข่ออนเซ็นวางด้านบน',
      'โรยต้นหอมซอยและสาหร่ายโนริ',
      'เสิร์ฟทันทีตอนร้อน',
    ],
    tips: 'ต้มน้ำซุปนาน ๆ จะได้รสเข้มข้น',
    platingTips: null,
    nutrition: { calories: 480, protein: 25, fat: 15, carbs: 60, sugar: 4, sodium: 1500 },
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 890,
    isRecommended: true,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '8',
    name: 'ข้าวหน้าปลาแซลมอน สไตล์บ้านฉัน',
    emoji: '🍣',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Salmon_and_shrimp_don_by_jetalone_in_Akihabara.jpg/1280px-Salmon_and_shrimp_don_by_jetalone_in_Akihabara.jpg',
    category: 'อาหารจานเดียว',
    country: 'ญี่ปุ่น',
    cookTimeMinutes: 15,
    prepTimeMinutes: 10,
    difficulty: 'ง่าย',
    servings: 2,
    isOfficial: false,
    uploaderName: 'ครัวโตเกียวซัง',
    rating: 4.4,
    reviewCount: 61,
    ingredients: [
      'ข้าวญี่ปุ่นหุงสุก 2 ถ้วย',
      'ปลาแซลมอนซาชิมิ 150 กรัม',
      'ซีอิ๊วญี่ปุ่น 2 ช้อนโต๊ะ',
      'วาซาบิ ตามชอบ',
      'สาหร่ายโนริฝอย และงาขาว สำหรับโรยหน้า',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'หั่นปลาแซลมอนเป็นแผ่นบาง',
      'ตักข้าวญี่ปุ่นใส่ชาม',
      'จัดเรียงแซลมอนด้านบนข้าว',
      'ราดซีอิ๊วญี่ปุ่นเล็กน้อย',
      'โรยสาหร่ายฝอยและงาขาว',
      'เสิร์ฟพร้อมวาซาบิ',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '9',
    name: 'ทาโคยากิ',
    emoji: '🐙',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Takoyaki_in_Osaka.jpg/1280px-Takoyaki_in_Osaka.jpg',
    category: 'สแน็ค',
    country: 'ญี่ปุ่น',
    cookTimeMinutes: 30,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.5,
    reviewCount: 78,
    ingredients: [
      'แป้งทาโคยากิ 200 กรัม',
      'น้ำซุปดาชิ 500 มล.',
      'ไข่ไก่ 2 ฟอง',
      'หนวดปลาหมึกหั่นชิ้น 150 กรัม',
      'ต้นหอมซอย, ผงคัตสึโอะบุชิ, ซอสทาโคยากิ และมายองเนส สำหรับตกแต่ง',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ผสมแป้งทาโคยากิกับน้ำซุปดาชิและไข่ให้เข้ากัน',
      'ตั้งกระทะทาโคยากิให้ร้อน ทาน้ำมันบาง ๆ',
      'เทแป้งลงในหลุมพิมพ์ ใส่หนวดปลาหมึกและต้นหอม',
      'ใช้ไม้แหลมพลิกลูกทาโคยากิให้กลมทั่วทุกด้าน',
      'ทอดจนสุกเหลืองกรอบนอกนุ่มใน',
      'ราดซอสทาโคยากิ มายองเนส และโรยผงคัตสึโอะบุชิ',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '10',
    name: 'ข้าวผัดไข่เค็มจีน',
    emoji: '🍳',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Salted_egg_fried_rice.jpg/1280px-Salted_egg_fried_rice.jpg',
    category: 'อาหารจานเดียว',
    country: 'จีน',
    cookTimeMinutes: 20,
    prepTimeMinutes: 5,
    difficulty: 'ง่าย',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.5,
    reviewCount: 102,
    ingredients: [
      'ข้าวสวย (ค้างคืน) 2 ถ้วย',
      'ไข่เค็ม 2 ฟอง',
      'ไข่ไก่ 1 ฟอง',
      'กระเทียม 3 กลีบ',
      'ต้นหอมซอย 2 ต้น',
      'ซีอิ๊วขาว 1 ช้อนโต๊ะ',
      'น้ำมันพืช 2 ช้อนโต๊ะ',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'แยกไข่แดงเค็มออกมาบดหยาบ ๆ',
      'ตั้งกระทะใส่น้ำมัน เจียวกระเทียมให้หอม',
      'ใส่ไข่ไก่และไข่แดงเค็มลงผัดให้เป็นเกล็ด',
      'ใส่ข้าวสวย คลุกให้เข้ากันทั่วกระทะ',
      'ปรุงรสด้วยซีอิ๊วขาว ผัดให้ข้าวร่อน',
      'โรยต้นหอม เสิร์ฟร้อน ๆ',
    ],
    tips: null,
    platingTips: null,
    nutrition: { calories: 380, protein: 12, fat: 14, carbs: 48, sugar: 1, sodium: 920 },
    dietTags: ['เด็ก'],
    season: 'ตลอดปี',
    viewCount: 540,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '11',
    name: 'หมูผัดเปรี้ยวหวาน',
    emoji: '🍖',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Sweet_and_sour_pork.jpg/1280px-Sweet_and_sour_pork.jpg',
    category: 'อาหารจานเดียว',
    country: 'จีน',
    cookTimeMinutes: 25,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: false,
    uploaderName: 'ครัวเจ๊กิมจากกวางตุ้ง',
    rating: 4.3,
    reviewCount: 49,
    ingredients: [
      'หมูสันคอ 250 กรัม',
      'แป้งข้าวโพด 3 ช้อนโต๊ะ',
      'สับปะรด 1/2 ถ้วย',
      'พริกหวานสีต่าง ๆ 1 ถ้วย',
      'ซอสมะเขือเทศ 3 ช้อนโต๊ะ',
      'น้ำตาลทราย 2 ช้อนโต๊ะ',
      'น้ำส้มสายชู 2 ช้อนโต๊ะ',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'หั่นหมูเป็นชิ้นพอดีคำ คลุกแป้งข้าวโพดแล้วทอดให้กรอบ',
      'ผัดพริกหวานและสับปะรดในกระทะให้หอม',
      'ผสมซอสมะเขือเทศ น้ำตาล และน้ำส้มสายชูเป็นซอสเปรี้ยวหวาน',
      'เทซอสลงผัดในกระทะให้เดือดข้น',
      'ใส่หมูทอดลงคลุกให้ซอสเคลือบทั่ว',
      'ตักเสิร์ฟร้อน ๆ กับข้าวสวย',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '12',
    name: 'เกี๊ยวซ่าจีนนึ่ง',
    emoji: '🥟',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Pot-stickers.jpg/1280px-Pot-stickers.jpg',
    category: 'สแน็ค',
    country: 'จีน',
    cookTimeMinutes: 35,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.6,
    reviewCount: 85,
    ingredients: [
      'แผ่นเกี๊ยว 20 แผ่น',
      'หมูสับ 200 กรัม',
      'กะหล่ำปลีสับละเอียด 1 ถ้วย',
      'ขิงสับ 1 ช้อนชา',
      'ซีอิ๊วขาว 1 ช้อนโต๊ะ',
      'น้ำมันงา 1 ช้อนชา',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ผสมหมูสับ กะหล่ำปลี ขิง ซีอิ๊วขาว และน้ำมันงาให้เข้ากัน',
      'ตักไส้ใส่แผ่นเกี๊ยว พับจีบขอบให้สวย',
      'นึ่งในลังถึงที่ทาน้ำมันไว้ประมาณ 12-15 นาที',
      'เสิร์ฟพร้อมน้ำจิ้มซีอิ๊วผสมน้ำส้มสายชู',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '13',
    name: 'บิบิมบับ',
    emoji: '🍲',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Bibimbap_салат.jpg/1280px-Bibimbap_салат.jpg',
    category: 'อาหารจานเดียว',
    country: 'เกาหลี',
    cookTimeMinutes: 30,
    prepTimeMinutes: 20,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.7,
    reviewCount: 156,
    ingredients: [
      'ข้าวสวย 2 ถ้วย',
      'เนื้อวัวสไลซ์ 150 กรัม',
      'แครอทซอย 1/2 ถ้วย',
      'ผักโขมลวก 1 ถ้วย',
      'ถั่วงอกลวก 1 ถ้วย',
      'เห็ดหอมหั่น 1/2 ถ้วย',
      'ไข่ดาว 1 ฟอง',
      'ซอสโคชูจัง 2 ช้อนโต๊ะ',
      'น้ำมันงา 1 ช้อนโต๊ะ',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ผัดเนื้อวัวกับซอสถั่วเหลืองและกระเทียมให้สุก',
      'ผัดผักแต่ละชนิดแยกกันให้สุกพอดี',
      'ตักข้าวสวยใส่ชาม จัดเรียงผักและเนื้อวัวรอบ ๆ',
      'วางไข่ดาวตรงกลาง',
      'หยอดซอสโคชูจังและน้ำมันงา',
      'คลุกทุกอย่างให้เข้ากันก่อนรับประทาน',
    ],
    tips: null,
    platingTips: null,
    nutrition: { calories: 520, protein: 30, fat: 18, carbs: 55, sugar: 8, sodium: 1100 },
    dietTags: ['สุขภาพ', 'คลีน'],
    season: 'ตลอดปี',
    viewCount: 670,
    isRecommended: true,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '14',
    name: 'ต๊อกบกกี เผ็ดนัวสูตรป้าซอ',
    emoji: '🌶️',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Tteokbokki_02.jpg/1280px-Tteokbokki_02.jpg',
    category: 'สแน็ค',
    country: 'เกาหลี',
    cookTimeMinutes: 20,
    prepTimeMinutes: 5,
    difficulty: 'ง่าย',
    servings: 2,
    isOfficial: false,
    uploaderName: 'ป้าซอข้างบ้าน',
    rating: 4.8,
    reviewCount: 203,
    ingredients: [
      'ต๊อก (เค้กข้าวเกาหลี) 300 กรัม',
      'ปลาเส้นเกาหลี 100 กรัม',
      'ซอสโคชูจัง 3 ช้อนโต๊ะ',
      'ซอสพริกเกาหลี (โคชูการุ) 1 ช้อนโต๊ะ',
      'น้ำตาลทราย 2 ช้อนโต๊ะ',
      'น้ำซุปหรือน้ำเปล่า 400 มล.',
      'ต้นหอม และไข่ต้ม สำหรับเสิร์ฟ',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'แช่ต๊อกในน้ำอุ่นให้นิ่มก่อนปรุง',
      'ตั้งน้ำซุปให้เดือด ละลายซอสโคชูจัง โคชูการุ และน้ำตาล',
      'ใส่ต๊อกและปลาเส้นลงต้มจนนิ่มและซอสข้นเหนียว',
      'คนเรื่อย ๆ ไม่ให้ต๊อกติดก้นกระทะ',
      'ตักเสิร์ฟพร้อมต้นหอมซอยและไข่ต้ม',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: ['เด็ก', 'มังสวิรัติ'],
    season: 'ตลอดปี',
    viewCount: 1800,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '15',
    name: 'กิมจิจิเก',
    emoji: '🍲',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Kimchi_jjigae.jpg/1280px-Kimchi_jjigae.jpg',
    category: 'ต้ม/แกง',
    country: 'เกาหลี',
    cookTimeMinutes: 30,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: true,
    uploaderName: null,
    rating: 4.5,
    reviewCount: 67,
    ingredients: [
      'กิมจิดอง 1 ถ้วย',
      'หมูสามชั้นหั่นชิ้น 150 กรัม',
      'เต้าหู้ก้อน 1 ก้อน',
      'ต้นหอม 2 ต้น',
      'ซอสโคชูจัง 1 ช้อนโต๊ะ',
      'น้ำซุปหรือน้ำเปล่า 600 มล.',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'ผัดหมูสามชั้นในหม้อจนมันออกและสุกหอม',
      'ใส่กิมจิลงผัดรวมกันสักครู่',
      'เติมน้ำซุป ต้มจนเดือด',
      'ปรุงรสด้วยซอสโคชูจังตามชอบ',
      'ใส่เต้าหู้หั่นชิ้น ต้มจนเดือดอีกครั้ง',
      'โรยต้นหอม เสิร์ฟร้อน ๆ',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
  {
    legacyId: '16',
    name: 'ไก่ทอดเกาหลีซอสยังนยอม',
    emoji: '🍗',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Korean.fried.chicken.jpg/1280px-Korean.fried.chicken.jpg',
    category: 'อาหารจานเดียว',
    country: 'เกาหลี',
    cookTimeMinutes: 40,
    prepTimeMinutes: 10,
    difficulty: 'ปานกลาง',
    servings: 2,
    isOfficial: false,
    uploaderName: 'ครัวโซลซิตี้',
    rating: 4.7,
    reviewCount: 174,
    ingredients: [
      'ปีกไก่หรือน่องไก่ 500 กรัม',
      'แป้งทอดกรอบ 1 ถ้วย',
      'ซอสโคชูจัง 2 ช้อนโต๊ะ',
      'น้ำผึ้ง 2 ช้อนโต๊ะ',
      'กระเทียมสับ 1 ช้อนโต๊ะ',
      'ซีอิ๊วถั่วเหลือง 1 ช้อนโต๊ะ',
      'งาขาว สำหรับโรยหน้า',
    ],
    ingredientItems: NO_ITEMS,
    steps: [
      'คลุกไก่กับแป้งทอดกรอบให้ทั่ว',
      'ทอดไก่ในน้ำมันร้อนจนกรอบเหลืองสุก',
      'ผัดกระเทียมสับให้หอม ใส่ซอสโคชูจัง น้ำผึ้ง และซีอิ๊วถั่วเหลือง',
      'เคี่ยวซอสจนข้นเล็กน้อย',
      'ใส่ไก่ทอดลงคลุกกับซอสให้เคลือบทั่ว',
      'โรยงาขาว เสิร์ฟทันที',
    ],
    tips: null,
    platingTips: null,
    nutrition: null,
    dietTags: [],
    season: 'ตลอดปี',
    viewCount: 0,
    isRecommended: false,
    videoUrl: null,
    createdAt: new Date('2025-06-01'),
  },
];

export interface ReviewSeed {
  recipeLegacyId: string;
  userName: string;
  rating: number;
  content: string;
  createdAt: Date;
  likeCount: number;
  replies: { userName: string; content: string; createdAt: Date }[];
}

export const reviewSeeds: ReviewSeed[] = [
  {
    recipeLegacyId: '1',
    userName: 'คุณมิ้นท์',
    rating: 5,
    content: 'อร่อยมาก ทำตามสูตรแล้วได้รสชาติเหมือนร้านเลย!',
    createdAt: new Date('2025-07-10'),
    likeCount: 12,
    replies: [{ userName: 'แอดมิน', content: 'ขอบคุณที่รีวิวค่ะ 🙏', createdAt: new Date('2025-07-11') }],
  },
  {
    recipeLegacyId: '1',
    userName: 'เชฟน้อย',
    rating: 4,
    content: 'รสชาติดี แต่แนะนำเพิ่มพริกอีกนิดจะแซ่บกว่านี้',
    createdAt: new Date('2025-07-05'),
    likeCount: 5,
    replies: [],
  },
  {
    recipeLegacyId: '2',
    userName: 'คุณแป้ง',
    rating: 5,
    content: 'ต้มยำกุ้งสูตรนี้เด็ดสุด ๆ กลมกล่อมทุกรส',
    createdAt: new Date('2025-06-20'),
    likeCount: 28,
    replies: [],
  },
  {
    recipeLegacyId: '4',
    userName: 'FoodLover',
    rating: 4.5,
    content: 'คาโบนาร่าเนื้อครีมมม ทำง่ายมาก',
    createdAt: new Date('2025-07-01'),
    likeCount: 8,
    replies: [],
  },
];

export interface CommentSeed {
  recipeLegacyId: string;
  userName: string;
  content: string;
  createdAt: Date;
  mentions: string[];
  replies: { userName: string; content: string; createdAt: Date; mentions: string[] }[];
}

export const commentSeeds: CommentSeed[] = [
  {
    recipeLegacyId: '1',
    userName: 'คุณบี',
    content: 'ใช้กระเพราแดงได้ไหมคะ? 🌿',
    createdAt: new Date('2025-07-08'),
    mentions: [],
    replies: [
      {
        userName: 'แอดมิน',
        content: '@คุณบี ได้เลยค่ะ รสชาติจะต่างกันเล็กน้อย',
        createdAt: new Date('2025-07-08T14:30:00'),
        mentions: ['คุณบี'],
      },
    ],
  },
  {
    recipeLegacyId: '1',
    userName: 'คุณต้น',
    content: 'อร่อยมากครับ 👍 ทำให้แฟนชอบเลย',
    createdAt: new Date('2025-07-03'),
    mentions: [],
    replies: [],
  },
  {
    recipeLegacyId: '2',
    userName: 'คุณหนึ่ง',
    content: 'ถ้าไม่มีกุ้งสด ใช้กุ้งแช่แข็งได้ไหม?',
    createdAt: new Date('2025-06-15'),
    mentions: [],
    replies: [
      {
        userName: 'เชฟโบ',
        content: '@คุณหนึ่ง ได้ครับ แต่ลดเวลาต้มลงนิดหน่อย',
        createdAt: new Date('2025-06-16'),
        mentions: ['คุณหนึ่ง'],
      },
    ],
  },
];
